mateweather/mateweather-applet.c
without this commit the temperature displays under the icon at horizontal panels and conversely at vertical panels
=> GTK3: fix panel orientation from weather applet

battstat/power-management.c
- Use MI header file
- Fix apminfo struct name
=> battstat applet: fix NetBSD APM support

charpick/charpick.c, charpick/charpick.h, charpick/properties.c, geyes/themes.c
Removing something that users see and interact with only to fix some "deprecations" wasn't right. Let's get the icons back.
=> charpick, geyes: restore icons on buttons in prefs dialogs

configure.ac
[] is misrecognized by autoconf and broken configure script is
generated.
=> Use `test' instead of `[ ]' in configure.ac

configure.ac
The dependency is not really needed; depending on GTK+ should be enough
to guarantee the presence of a spec-compliant icon theme.
=> drop dpendency to mate-icon-theme

drivemount/drive-button.c
This fixes the invisible text for GTK+ 3 themes which don't support mate-panel explicitly. Themes could still overwrite the background if they want in the usual way.
=> drivemount: Don't remove background

stickynotes/stickynotes.c
adapted from https://git.gnome.org/browse/gnome-applets/commit/?id=75836cbd9198b0ceb55498147932da957d158563
=>  stickynotes: correctly apply chosen font type in GTK+3 build

command/command.c, timerapplet/timerapplet.c
This makes the license of the project consistent.
See: https://github.com/mate-desktop/mate-applets/issues/183
=> Re-license Command and Timer applets under GPL-2+

cpufreq/src/cpufreq-applet.c
Stop BlackMATE, possibly other themes from cutting off the end of the units label and get rid of an #if block for GTK 3.19 at the same time.  GTK 3.19 seemed to pad the end of this label a bit, not so with released GTK 3.20.
=> GTK 3.20 cpufreq: fix themes clipping units label

configure.ac, netspeed/src/netspeed.c
Using GtkColorButton or GtkColorChooser makes it possible to get rid of deps to libmate-desktop.
MateColorButton was an implementation from Stefano to make my life easier for themes with using a own mate-color-chooser.
But using this lib for an app which set only the line color for a graph does not make any sense.
Here using gtk stuff is sufficient.
=> drop dependency to libmate-deskop

charpick/charpick.c
Not sure if I should really force zero border width. It fixes the warning, but similar mate-panel fixes say something about setting border in themes. Feel free to correct that commit guys, I'm not so familiar with theming.
=> two charpick applet fixes

drivemount/drive-button.c
Now I don't know if I do it right, because this time these CSS settings are in class init function, and in fact DriveButton is inherited from GtkButton. So maybe the right thing is to set a class name, not a widget name. But it seems to work anyway, and ```gtk_widget_class_set_css_name``` is only available for GTK+ >= 3.20, while I need to make it work for older versions too. Feel free to make any corrections. :slightly_smiling_face:
=> drivemount: fix runtime warnings with GTK+ 3.20/22

multiload/docs/C/index.docbook, multiload/linux-proc.c, multiload/load-graph.c, multiload/main.c, multiload/org.mate.panel.applet.multiload.gschema.xml.in, multiload/properties.c
Load graph is scaled automatically according to average load value, like old time xsysload program. If Load  grows over 1, there will be a line signalizing load is over 1 and whole graph is scaled accordingly. When Load goes over 2, there will be two lines etc. Similarly when Load goes down,grid lines will be removed.
Color of grid line can be set in properties. Schema was updated to keep the value of grid line color.
Notes for reviewer:
Most of diff is trailing blanks or whitespaces in empty lines which were automatically changed by atom editor.
Real heavy changes are in load-graph.c in function load_graph_draw()
=> Autoscale load

charpick/charpick.c, cpufreq/src/cpufreq-applet.c, stickynotes/stickynotes_applet.c
avoid deprecated:
- gdk_screen_get_width/height
- gdk_screen_width/height
=> avoid deprecated gdk_screen_get_width/height and gdk_screen_width/height

drivemount/drive-button.c, drivemount/drive-list.c
warning identified by raveit65
misleading_indentation was just wrong source code formatting
maybe_unintialized warning was just plain wrong, but easy to make compiler happy
=> Get rid of misleading_indentation and maybe-uninitialized warning during build

drivemount/drive-button.c, drivemount/drive-button.h, drivemount/drive-list.c, drivemount/drive-list.h, drivemount/drivemount.c
When color is changed in dconf-editor, it is immediately shown in applet, no need to remount.
=> GSettings change recognized dynamically

stickynotes/stickynotes.c
fixes https://github.com/mate-desktop/mate-applets/issues/236
taken from:
https://git.gnome.org/browse/gnome-applets/commit/?id=e189ba213c0f8db876dd020d1d80b9f8b576dd75
=> stickynotes: fix text selection

charpick/charpick.c, cpufreq/src/cpufreq-applet.c, stickynotes/stickynotes_applet.c
This commit reverts:
https://github.com/mate-desktop/mate-applets/commit/d809e57c7b09f545f1cf847f514fa738d44ac2b3
https://github.com/mate-desktop/mate-applets/commit/2f5515815c1f6c9b66f85d6ec228aad7aea0b441
And it applies an alternative to fix the deprecated functions:
gdk_screen_get_width
gdk_screen_get_height
gdk_screen_width
gdk_screen_height
=> WidthOfScreen and HeightOfScreen implementation

mateweather/main.c, mateweather/mateweather-applet.c, mateweather/mateweather.h
Reverting the commits is more a quick and dirty, but i will do the same for fedora to avoid spam in my mailbox from users who files out a rhbz report.
Maybe someone find a real fix for clock-applet crashes with those commits.
So, i will leave that PR open.
Fixes https://github.com/mate-desktop/libmateweather/issues/51
=> Fix clock applet crashes

cpufreq/src/cpufreq-applet.c
The CPU Freq applet overrides the libmate-panel-applet size calculation, so it then needs to account for scaling on its own...
=> Fix cpufreq applet spacing on HiDPI displays

cpufreq/src/cpufreq-applet.c
Fix https://github.com/mate-desktop/mate-applets/issues/175 by removing old GTK 2 leftovers that never worked right and using  gtk_widget_get_preferred_size and gtk_widget_get_preferred_width to so the same job.  Same coding used to set frequency label, unit label, and percentage label widths. This also finally gets rid of the maximum applet size that under so many conditions clipped labels and apparently was responsible for #175
=> Ensure CPU frequency label is always displayed if selected

cpufreq/src/cpufreq-popup.c
Also stop any other segfaults caused by failure of deprecated gtk_action_group_get_action to return the name of the active item. With GTK 3.23.0 cpufreq_popup_menu_set_active sends invalid name information for userspace governors.
=> cpufreq: stop segfault with gtk3.23

mateweather/mateweather-dialog.c
Will be needed if this is ever ported to in-process. If all of mate-applets including stickynotes was ported to in-process (needed for wayland, GTK4, or any other environment w/o GtkPlug/GtkSocket/Xembed) the font applied here is applied to stickynotes too if the cssprovider is for screen, as in that case the "process" in which the provider is valid becomes the entire panel.
=> weather: Use widget name in cssprovider to limit it to just this applet

mateweather/mateweather-dialog.c
This works the exact same way gtk_css_provider_get_default works internally, except that we handle a static cssprovider ourselves. Made necessary by https://gitlab.gnome.org/GNOME/gtk/merge_requests/257
=> Avoid newly deprecated gtk_css_provider_get_default

configure.ac
When run `make`, the output looks like this:
```
GEN      ku_IQ/ku_IQ.mo
GEN    ku_IQ/
GEN      hy/hy.mo
GEN    hy/
GEN      en_CA/en_CA.mo
GEN    en_CA/
GEN      fy/fy.mo
GEN    fy/
GEN      kab/kab.mo
GEN    kab/
```
=> Silent output when building.

.travis.yml
Currently building for debian and ubuntu is disabled.
Their builds failed with 
```
CCLD     mate-cpufreq-selector
/usr/bin/ld: cannot find -lcpupower
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:586: mate-cpufreq-selector] Error 1
make[5]: Leaving directory '/rootdir/cpufreq/src/cpufreq-selector'
make[4]: *** [Makefile:501: all] Error 2
make[4]: Leaving directory '/rootdir/cpufreq/src/cpufreq-selector'
make[3]: *** [Makefile:636: all-recursive] Error 1
make[3]: Leaving directory '/rootdir/cpufreq/src'
make[2]: *** [Makefile:594: all-recursive] Error 1
make[2]: Leaving directory '/rootdir/cpufreq'
make[1]: *** [Makefile:555: all-recursive] Error 1
make[1]: Leaving directory '/rootdir'
make: *** [Makefile:487: all] Error 2
!!! ERROR: run command [docker exec -t …
```
=> enable Travis CI support

accessx-status/docs/C/index.docbook, battstat/docs/C/index.docbook, charpick/help/C/index.docbook, cpufreq/help/C/index.docbook, drivemount/help/C/index.docbook, geyes/docs/C/index.docbook, mateweather/docs/C/index.docbook, multiload/docs/C/index.docbook, netspeed/help/C/index.docbook, stickynotes/docs/C/index.docbook, trashapplet/docs/C/index.docbook
The ENTITY is expanded in i18n process, and legal.xml file
is never read.
Example `diff /usr/share/help/ca/mate-geyes/index.docbook geyes/docs/ca/index.docbook `
```diff
3d2
< <!ENTITY legal SYSTEM "legal.xml">
43,58d41
<   <legalnotice id="legalnotice">
< 	<para>Es concedeix el permís per copiar, distribuir i / o modificar aquest document sota els termes de la GFDL (GNU Free Documentation License), versió 1.1 o qualsevol versió posterior publicada per la Free Software Foundation que tinguin les seccions invariants, i sense cap text a la portada. Podeu trobar una còpia de la GFDL en aquest <ulink type="help" url="help:fdl">enllaç</ulink> o bé al fitxer COPYING-DOCS que es distribueix amb aquest manual.</para>
<          <para>Aquest manual forma part d'una col·lecció de manuals de MATE …
```
=> Help: Use XInclude instead of ENTITY for legal.xml

battstat/battstat_applet.c, stickynotes/stickynotes.c
```
battstat_applet.c:755:3: warning: Use of memory after it is freed
static_global_teardown (battstat);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
stickynotes.c:674:24: warning: Use of memory after it is freed
stickynotes->notes = g_list_remove(stickynotes->notes, note);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Fix use-after-free clang warning

cpufreq/src/cpufreq-monitor.c, cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c, netspeed/src/backend.c, trashapplet/src/trashapplet.c
```C
void
g_list_free_full (GList *list,
GDestroyNotify free_func);
```
Convenience method, which frees all the memory used
by a GList, and calls `free_func` on every element's
data.
https://developer.gnome.org/glib/stable/glib-Doubly-Linked-Lists.html#g-list-free-full
=> Use g_list_free_full() convenience function

multiload/linux-proc.c
=> multiload: filter-out non-local disks and user mounts

command/command.c
=> treat output as utf8 when limiting width. fixes #374

multiload/linux-proc.c, multiload/org.mate.panel.applet.multiload.gschema.xml.in, multiload/properties.c
Since glibtop does not support NVMe drives, we rely on /proc/diskstats
to tell use load information for NVMe drives. If diskstats is not
present it returns to glibtop as a fallback.
This also adds a preference to toggle this behavior (default is glibtop).
Fixes #290
=> multiload: Use /proc/diskstats for NVMe drives

configure.ac, cpufreq/src/cpufreq-monitor-libcpufreq.c, cpufreq/src/cpufreq-selector/cpufreq-selector-libcpufreq.c
Ported from gnome-applets, see
git diff e48b2d73~..5882df7f cpufreq/ configure.ac
on the gnome-applets repository.
Fixes mate-desktop/mate-applets#238.
=> Make cpufreq builds independent from kernel header version.

cpufreq/src/cpufreq-selector/cpufreq-selector-libcpufreq.c, cpufreq/src/cpufreq-selector/cpufreq-selector-procfs.c, cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c
```
cpufreq-selector-sysfs.c:244:18: warning: taking the absolute value of unsigned type ‘guint’ {aka ‘unsigned int’} has no effect [-Wabsolute-value]
244 |   current_dist = abs (frequency - f);
|                  ^~~
--
cpufreq-selector-procfs.c:187:7: warning: taking the absolute value of unsigned type ‘guint’ {aka ‘unsigned int’} has no effect [-Wabsolute-value]
187 |   if (abs (sc_max - frequency) < abs (frequency - sc_min))
|       ^~~
cpufreq-selector-procfs.c:187:34: warning: taking the absolute value of unsigned type ‘guint’ {aka ‘unsigned int’} has no effect [-Wabsolute-value]
187 |   if (abs (sc_max - frequency) < abs (frequency - sc_min))
|                                  ^~~
--
cpufreq-selector-libcpufreq.c:109:18: warning: taking the absolute value of unsigned type ‘long …
```
=> cpufreq: remove -Wabsolute-value warning

netspeed/src/netspeed.c
```
netspeed.c:477:15: warning: variable ‘state’ set but not used [-Wunused-but-set-variable]
477 |  GtkStateType state;
|               ^~~~~
netspeed.c:476:15: warning: variable ‘ra’ set but not used [-Wunused-but-set-variable]
476 |  GdkRectangle ra;
|               ^~
```
=> netspeed: remove -Wunused-but-set-variable warning

drivemount/drive-button.c
```
drive-button.c:618:6: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
618 |      gtk_message_dialog_format_secondary_text (GTK_MESSAGE_DIALOG (dialog), error->message, NULL);
|      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> drivemount: remove -Wformat-nonliteral warning

.travis.yml
Now it can found the cpupower library when building:
https://travis-ci.org/mate-desktop/mate-applets/jobs/587805787#L875
=> ci: add cpupower build dependency to archlinux

configure.ac
Don't stop building when cpufreq.h isn't available.
=> build: fix building cpufreq-applet for s390x arch

battstat/power-management.c, cpufreq/src/cpufreq-applet.c, cpufreq/src/cpufreq-monitor-cpuinfo.c, cpufreq/src/cpufreq-monitor-libcpufreq.c, cpufreq/src/cpufreq-monitor-procfs.c, cpufreq/src/cpufreq-monitor-sysfs.c, cpufreq/src/cpufreq-monitor.c, cpufreq/src/cpufreq-popup.c, cpufreq/src/cpufreq-prefs.c, cpufreq/src/cpufreq-selector/cpufreq-selector-libcpufreq.c, cpufreq/src/cpufreq-selector/cpufreq-selector-procfs.c, cpufreq/src/cpufreq-selector/cpufreq-selector-sysfs.c, cpufreq/src/cpufreq-selector/cpufreq-selector.c, drivemount/drive-button.c, drivemount/drive-button.h
Fixes the warnings:
```
drive-button.h:66:13: warning: redundant redeclaration of ‘settings’ [-Wredundant-decls]
power-management.c:296:10: warning: redundant redeclaration of ‘acpi_linux_read’ [-Wredundant-decls]
cpufreq-selector.c:46:55: warning: redundant redeclaration of ‘cpufreq_selector_init’ [-Wredundant-decls]
cpufreq-selector.c:46:55: warning: redundant redeclaration of ‘cpufreq_selector_class_init’ [-Wredundant-decls]
cpufreq-selector-sysfs.c:47:51: warning: redundant redeclaration of ‘cpufreq_selector_sysfs_init’ [-Wredundant-decls]
cpufreq-selector-sysfs.c:47:51: warning: redundant redeclaration of ‘cpufreq_selector_sysfs_class_init’ [-Wredundant-decls]
cpufreq-selector-procfs.c:40:39: warning: redundant redeclaration of ‘cpufreq_selector_procfs_init’ [-Wredundant-decls] …
```
=> avoid redundant redeclarations

accessx-status/applet.c
accessx_status_applet_set_state_icon() passes the uninitialized variable surface to gtk_image_set_from_surface() leading to a crash. This patch starts surface as NULL.
=> Initialize "surface" before testing its value to avoid a crash.

configure.ac
and bump the required D-Bus version
this is a follow-up to #433, with the changes same as in https://github.com/mate-desktop/mate-settings-daemon/pull/304
=> use ${datadir}/dbus-1/system.d as the default D-Bus config dir

drivemount/drive-list.c, drivemount/drive-list.h
```
/usr/bin/ld: drive-list.o:/home/robert/mate-applets/drivemount/drive-list.h:68: multiple definition of `settings'; drivemount.o:/home/robert/mate-applets/drivemount/drive-list.h:68: first defined here
```
=> Fix build using gcc 10 -fno-common flag

drivemount/drive-list.c, drivemount/drive-list.h, drivemount/drivemount.c
Test: setting check mark color on dconf-editor
=> drivemount: Remove global variable

configure.ac, netspeed/src/Makefile.am
Follow-up to #438.
How to test: check that all applets are still translated as before.
=> build: drop unused locale stuff

stickynotes/stickynotes_applet_callbacks.c
```
stickynotes_applet_callbacks.c:80:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
80 | stickynote_toggle_notes_visible ()
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> stickynotes: Remove strict-prototypes warning

accessx-status/applet.c, battstat/battstat-upower.c, charpick/charpick.c, cpufreq/src/cpufreq-applet.c, mateweather/mateweather-dialog.c, mateweather/mateweather-pref.c, multiload/linux-proc.c, multiload/load-graph.c, netspeed/src/netspeed.c
```
charpick.c:277:19: warning: unused variable ‘applet’ [-Wunused-variable]
277 |  MatePanelApplet *applet = MATE_PANEL_APPLET (curr_data->applet);
|                   ^~~~~~
--
charpick.c:645:19: warning: unused variable ‘applet’ [-Wunused-variable]
645 |  MatePanelApplet *applet = MATE_PANEL_APPLET (curr_data->applet);
|                   ^~~~~~
--
linux-proc.c:299:11: warning: unused variable ‘used’ [-Wunused-variable]
299 |     float used;
|           ^~~~
--
linux-proc.c:383:13: warning: unused variable ‘index’ [-Wunused-variable]
383 |         int index;
|             ^~~~~
linux-proc.c:422:13: warning: unused variable ‘max’ [-Wunused-variable]
422 |         int max;
|             ^~~
--
load-graph.c:109:13: warning: unused variable ‘grid_color’ [-Wunused-variable]
109 | …
```
=> Remove unused-variable warnings

cpufreq/src/cpufreq-applet.c, drivemount/drive-button.c, netspeed/src/netspeed.c, trashapplet/src/trash-empty.c
```
drive-button.c:170:1: warning: ‘_gtk_get_monitor_num’ defined but not used [-Wunused-function]
170 | _gtk_get_monitor_num (GdkMonitor *monitor)
| ^~~~~~~~~~~~~~~~~~~~
--
trash-empty.c:49:1: warning: ‘trash_empty_clear_pending’ defined but not used [-Wunused-function]
49 | trash_empty_clear_pending (gpointer user_data)
| ^~~~~~~~~~~~~~~~~~~~~~~~~
--
netspeed.c:125:1: warning: ‘add_markup_size’ defined but not used [-Wunused-function]
125 | add_markup_size(char **string, int size)
| ^~~~~~~~~~~~~~~
--
cpufreq-applet.c:284:1: warning: ‘get_max_text_width’ defined but not used [-Wunused-function]
284 | get_max_text_width (GtkWidget *widget,
| ^~~~~~~~~~~~~~~~~~
```
=> Remove unused-function warnings

battstat/acpi-freebsd.c, battstat/power-management.c
```
$ cppcheck --enable=all . 2> err.txt
$ grep unusedVariable err.txt 
battstat/acpi-freebsd.c:144:7: style: Unused variable: acline [unusedVariable]
battstat/power-management.c:437:9: style: Unused variable: err [unusedVariable]
```
=> Remove unused variable warning reported by cppcheck

battstat/acpi-freebsd.c
```
$ cppcheck --enable=all . 2> err.txt
$ grep knownConditionTrueFalse err.txt 
battstat/acpi-freebsd.c:200:12: style: Condition 'charging' is always true [knownConditionTrueFalse]
```
=> battstat: warning about boolean algebra reported by cppcheck

cpufreq/src/cpufreq-selector.c, mateweather/mateweather-dialog.c, multiload/linux-proc.c, multiload/load-graph.c
```
$ cppcheck --enable=all . 2> err.txt
$ grep unreadVariable err.txt 
cpufreq/src/cpufreq-selector.c:47:28: style: Variable 'selector' is assigned a value that is never used. [unreadVariable]
mateweather/mateweather-dialog.c:118:13: style: Variable 'count' is assigned a value that is never used. [unreadVariable]
multiload/linux-proc.c:419:19: style: Variable 'total' is assigned a value that is never used. [unreadVariable]
multiload/linux-proc.c:428:19: style: Variable 'total' is assigned a value that is never used. [unreadVariable]
multiload/load-graph.c:96:19: style: Variable 'combined' is assigned a value that is never used. [unreadVariable]
multiload/load-graph.c:157:20: style: Variable 'spacing' is assigned a value that is never used. [unreadVariable]
multiload/load-graph.c:212:20: …
```
=> Remove warning about assigned value is never used reported by cppcheck

.build.yml, configure.ac, netspeed/data/org.mate.panel.applet.netspeed.gschema.xml.in, netspeed/src/Makefile.am, netspeed/src/backend.c, netspeed/src/backend.h, netspeed/src/ieee80211.h, netspeed/src/netspeed-preferences.ui, netspeed/src/netspeed.c, netspeed/src/nl80211.h, po/POTFILES.in
Based on https://stackoverflow.com/questions/18062268/using-nl80211-h-to-scan-access-points
and https://mirrors.edge.kernel.org/pub/software/network/iw/iw-5.4.tar.gz
=> netspeed: add netlink support

stickynotes/stickynotes.c, stickynotes/util.c, stickynotes/util.h
```
util.c:46:4: warning: format not a string literal, format string not checked [-Wformat-nonliteral]
46 |    while(strftime(date, date_length, format, current) == 0);
|    ^~~~~
--
```
In contrast to `strftime`, [g_date_time_format](https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format) always produces a UTF-8 string.
=> stickynotes: Fix -Wformat-nonliteral warning

cpufreq/src/cpufreq-monitor.c
Test: Add cpufreq-monitor-applet on a VM.
https://github.com/mate-desktop/mate-applets/blob/ca4a3b697836a99590c1e81a0b263588609b647c/cpufreq/src/cpufreq-monitor-libcpufreq.c#L73-L80
=> cpufreq: -1 indicates error obtaining max frequency

battstat/apmlib/apm.h, battstat/apmlib/apmlib.c
`ac_line_status`, `battery_status`, `battery_flag`, `apm_info.bios.flags` are `unsigned short`.
arch/x86/kernel/apm_32.c
```C
static int proc_apm_show(struct seq_file *m, void *v)
{
unsigned short  bx;
unsigned short  cx;
unsigned short  dx;
int             error;
unsigned short  ac_line_status = 0xff;
unsigned short  battery_status = 0xff;
unsigned short  battery_flag   = 0xff;
int             percentage     = -1;
int             time_units     = -1;
char            *units         = "?";
if ((num_online_cpus() == 1) &&
!(error = apm_get_power_status(&bx, &cx, &dx))) {
ac_line_status = (bx >> 8) & 0xff;
battery_status = bx & 0xff;
if ((cx & 0xff) != 0xff)
percentage = cx & 0xff;
if (apm_info.connection_version > 0x100) {
battery_flag = (cx >> 8) & 0xff;
if (dx != 0xffff) {
units = (dx & …
```
=> battstat: invalidScanfArgType_int cppcheck warnings (/proc/apm)

battstat/battstat_applet.c, netspeed/src/netspeed.c
```
netspeed.c: In function 'update_quality_icon':
/usr/include/glib-2.0/glib/gmacros.h:813:63: warning: comparison of unsigned expression in '< 0' is always false [-Wtype-limits]
813 | #define CLAMP(x, low, high)  (((x) > (high)) ? (high) : (((x) < (low)) ? (low) : (x)))
|                                                               ^
netspeed.c:345:6: note: in expansion of macro 'CLAMP'
345 |  q = CLAMP(q, 0, 3); /* q out of range would crash when accessing qual_surfaces[q] */
|      ^~~~~
--
/usr/include/glib-2.0/glib/gmacros.h:811:63: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
811 | #define CLAMP(x, low, high)  (((x) > (high)) ? (high) : (((x) < (low)) ? (low) : (x)))
|                                                               ^ …
```
=> Remove -Wtype-limits warnings

timerapplet/timerapplet.c
```
timerapplet.c:293:17: warning: conversion from 'gdouble' {aka 'double'} to 'gint' {aka 'int'} may change value [-Wfloat-conversion]
293 |     duration += gtk_spin_button_get_value (applet->hours) * 3600;
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~
timerapplet.c:294:17: warning: conversion from 'gdouble' {aka 'double'} to 'gint' {aka 'int'} may change value [-Wfloat-conversion]
294 |     duration += gtk_spin_button_get_value (applet->minutes) * 60;
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~
timerapplet.c:295:17: warning: conversion from 'gdouble' {aka 'double'} to 'gint' {aka 'int'} may change value [-Wfloat-conversion]
295 |     duration += gtk_spin_button_get_value (applet->seconds);
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~
```
=> timerapplet: Use gtk_spin_button_get_value_as_int for int values

multiload/linux-proc.c
Restore user memory value which was updated on libgtop 2.32,
since the new value cannot be used to display multiple memory
areas.
https://github.com/GNOME/libgtop/commit/0580b2fb2ca8fdde2031c8aba991bafac64d8dbd
=> multiload: do not count shared memory twice on Linux

accessx-status/src/applet.c
```
applet.c:933:4: warning: array subscript 128 is above array bounds of 'ModifierStruct[7]' [-Warray-bounds]
933 |    accessx_status_applet_set_state_icon (sapplet, &modifiers[Mod5Mask], GTK_STATE_FLAG_INSENSITIVE);
|    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--
applet.c:928:4: warning: array subscript 128 is above array bounds of 'ModifierStruct[7]' [-Warray-bounds]
928 |    accessx_status_applet_set_state_icon (sapplet, &modifiers[Mod5Mask], GTK_STATE_FLAG_NORMAL);
|    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> accessx-status: array subscript 128 is above array bounds

trashapplet/src/trashapplet.c, trashapplet/src/xstuff.c
```
trashapplet.c:214:3: warning: missing initializer for field 'flags' of 'GtkTargetEntry' {aka 'const struct _GtkTargetEntry'} [-Wmissing-field-initializers]
214 |   const GtkTargetEntry drop_types[] = { { "text/uri-list" } };
|   ^~~~~
--
xstuff.c:45:2: warning: missing initializer for field 'blue' of 'GdkColor' {aka 'struct _GdkColor'} [-Wmissing-field-initializers]
45 |  GdkColor color = { 65535, 65535, 65535 };
|  ^~~~~~~~
```
=> trashapplet: Remove warning about missing initializer

geyes/src/geyes.c
```
$ LANG=C journalctl --no-pager --boot | grep dispose
Nov 27 21:49:40 localhost.localdomain mate-geyes-appl[1583]: ../gobject/gsignal.c:2613: signal 'dispose' is invalid for instance '0x1f2c1b0' of type 'GtkBox'
```
=> geyes: signal 'dispose' is invalid for instance 'ID' of type 'GtkBox'

geyes/src/geyes.c, geyes/src/geyes.h, geyes/src/themes.c
- Use g_debug instead of printf for logging
- Do not store folder separator at the end of theme_dir
- Use g_build_filename instead of g_strdup_printf
- Remove trailing white spaces
- Do not use tabs for code indent
=> geyes: do not use dirent.h nor PATH_MAX

mateweather/src/mateweather-applet.c
```
$ LANG=C journalctl --no-pager --boot | grep mateweather
Dec 11 21:32:06 localhost.localdomain mateweather-app[1617]: weather_info_get_icon_name: assertion 'info != NULL' failed
Dec 11 21:32:06 localhost.localdomain mateweather-app[1617]: weather_info_get_temp_summary: assertion 'info != NULL' failed
Dec 11 21:32:06 localhost.localdomain mateweather-app[1617]: weather_info_get_icon_name: assertion 'info != NULL' failed
```
=> mateweather: Avoid NULL pointer dereferences if there is no weather info

netspeed/data/netspeed-details.ui, netspeed/src/backend.c
I think IPv6 address box should go directly below IPv4 as IPv6 is the new standard.
Also, I think it looks better and more meaningful if address scope is added to the back of the address in brackets, not in front. This is also more consistent with display of IPv4 addresses.
=> netspeed: improve display of IPv6 addresses in device details.

geyes/src/geyes.c, geyes/src/geyes.h, geyes/src/themes.c
```
geyes.c:70:54: warning: conversion from ‘int’ to ‘gfloat’ {aka ‘float’} may change value [-Wconversion]
70 |     nx = x - MAX (width - eyes_applet->eye_width, 0) * xalign
|                                                      ^
geyes.c:70:12: warning: conversion from ‘gint’ {aka ‘int’} to ‘gfloat’ {aka ‘float’} may change value [-Wconversion]
70 |     nx = x - MAX (width - eyes_applet->eye_width, 0) * xalign
|            ^
geyes.c:71:10: warning: conversion from ‘int’ to ‘gfloat’ {aka ‘float’} may change value [-Wconversion]
71 |          - eyes_applet->eye_width / 2;
|          ^
geyes.c:72:56: warning: conversion from ‘int’ to ‘gfloat’ {aka ‘float’} may change value [-Wconversion]
72 |     ny = y - MAX (height - eyes_applet->eye_height, 0) * yalign
| …
```
=> geyes: Remove conversion warnings

mateweather/src/mateweather-applet.c, mateweather/src/mateweather-pref.c, mateweather/src/mateweather.h
```
mateweather-pref.c:173:120: warning: conversion to ‘gint’ {aka ‘int’} from ‘unsigned int’ may change the sign of the result [-Wsign-conversion]
173 |     gtk_combo_box_set_active(GTK_COMBO_BOX(pref->priv->basic_temp_combo), gw_applet->mateweather_pref.temperature_unit - 2);
|                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
mateweather-pref.c:175:115: warning: conversion to ‘gint’ {aka ‘int’} from ‘unsigned int’ may change the sign of the result [-Wsign-conversion]
175 |     gtk_combo_box_set_active(GTK_COMBO_BOX(pref->priv->basic_speed_combo), gw_applet->mateweather_pref.speed_unit - 2);
|                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~ …
```
=> mateweather: Remove conversion warnings

netspeed/src/netspeed-preferences.c
```
systemd-coredump[137882]: [LNK] Process 137875 (mate-netspeed-a) of user 1000 dumped core.
Stack trace of thread 137875:
#0  0x000000000040dafe on_network_device_combo_changed (mate-netspeed-applet + 0xdafe)
#1  0x00007fd8358316a9 _g_closure_invoke_va (libgobject-2.0.so.0 + 0x146a9)
#2  0x00007fd8358493a8 g_signal_emit_valist (libgobject-2.0.so.0 + 0x2c3a8)
#3  0x00007fd835849582 g_signal_emit (libgobject-2.0.so.0 + 0x2c582)
#4  0x00007fd83635fd65 gtk_combo_box_set_active_internal.lto_priv.0 (libgtk-3.so.0 + 0x173d65)
#5  0x00007fd836360113 gtk_combo_box_set_active (libgtk-3.so.0 + 0x174113)
#6  0x000000000040de9f fill_device_combo (mate-netspeed-applet + 0xde9f)
#7  0x000000000040df41 netspeed_preferences_new (mate-netspeed-applet + 0xdf41)
#8  0x000000000040b5de settings_cb …
```
=> netspeed-preferences: disconnect a signal handler on finalize

trashapplet/src/trashapplet.c
Remove the warning
```
trashapplet.c:53:29: warning: no previous prototype for 'trash_applet_get_type' [-Wmissing-prototypes]
53 | G_DEFINE_TYPE (TrashApplet, trash_applet, PANEL_TYPE_APPLET);
|                             ^~~~~~~~~~~~
```
=> trashapplet: boilerplate final class

netspeed/src/netspeed.c
Remove runtime warning:
```
glibtop(c=30618): [WARNING] Failed to open "/sys/class/net//statistics/rx_packets": No such file or directory
glibtop(c=30618): [WARNING] Failed to open "/sys/class/net//statistics/tx_packets": No such file or directory
glibtop(c=30618): [WARNING] Failed to open "/sys/class/net//statistics/rx_bytes": No such file or directory
glibtop(c=30618): [WARNING] Failed to open "/sys/class/net//statistics/tx_bytes": No such file or directory
glibtop(c=30618): [WARNING] Failed to open "/sys/class/net//statistics/rx_errors": No such file or directory
glibtop(c=30618): [WARNING] Failed to open "/sys/class/net//statistics/tx_errors": No such file or directory
glibtop(c=30618): [WARNING] Failed to open "/sys/class/net//statistics/collisions": No such file or directory
```
=> netspeed: g_settings_get_string always returns a newly-allocated string

multiload/src/netspeed.h
Commit c85a5cf5 changed the definition to use guint64 rather than
gulong, but did not update the declaration in netspeed.h to match.
=> multiload: fix netspeed_add signature

cpufreq/src/cpufreq-selector/Makefile.am
Commit 4cb6f915 added cpufreq-selector-sysfs.[ch] to
mate_cpufreq_selector_SOURCES for the !HAVE_LIBCPUFREQ case, but they
were already unconditionally part of that. Including them twice leads to
duplicate definitions for the symbols defined by them.
=> cpufreq: fix cpufreq-selector-sysfs duplicate definitions

netspeed/src/netspeed.c
```
netspeed.c:1567:14: warning: unused variable ‘info’ [-Wunused-variable]
1567 |     DevInfo *info;
|              ^~~~
```
=> netspeed: Remove -Wunused-variable warning

charpick/charpick.c, charpick/charpick.h
Applied following patches by @muktupavels
* https://gitlab.gnome.org/GNOME/gnome-applets/-/commit/36f313d880aef4df2925a1fce585fa820429d4fd
* https://gitlab.gnome.org/GNOME/gnome-applets/-/commit/19c7ccdc26094988c979fa2ee9ace315acfa9f5e
=> Fix #372 by using GtkInvisible widget

geyes/src/geyes.c
Problem: when the mouse pointer is between two eyes, the left one is correct oriented; however the right one is wrongly oriented 
I discovered that this is due to the fact that it is not computed the offset between the single eye widget and their parent window.
Correct views:
To compute the correct pupil position, we should consider the offset
between the eye widget and their parent window.
Signed-off-by: Goffredo Baroncelli <kreijack@inwind.it>
=> geyes: consider the offset widget <-> window

charpick/charpick.c
```
Direct leak of 22 byte(s) in 1 object(s) allocated from:
#0 0x7f4d9c24d93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7f4d9a9f94df in g_malloc ../glib/gmem.c:106
#2 0x7f4d9a9f9822 in g_malloc_n ../glib/gmem.c:344
#3 0x7f4d9aa1be35 in g_strdup ../glib/gstrfuncs.c:361
#4 0x405e63 in build_table /home/robert/builddir.gcc/mate-applets/charpick/charpick.c:450
#5 0x407b7c in charpicker_applet_fill /home/robert/builddir.gcc/mate-applets/charpick/charpick.c:797
#6 0x407ef8 in charpicker_applet_factory /home/robert/builddir.gcc/mate-applets/charpick/charpick.c:870
#7 0x7f4d9c184673 in mate_panel_applet_marshal_BOOLEAN__STRING /home/robert/builddir.gcc/mate-panel/libmate-panel-applet/mate-panel-applet-marshal.c:122
#8 0x7f4d9ab08ea5 in g_closure_invoke ../gobject/gclosure.c:830 …
```
=> charpick: fix memory leak

command/src/command.c
```
Direct leak of 9 byte(s) in 1 object(s) allocated from:
#0 0x7fa3b813b93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7fa3b6e0d4df in g_malloc ../glib/gmem.c:106
#2 0x7fa3b6e0d822 in g_malloc_n ../glib/gmem.c:344
#3 0x7fa3b6e2fe35 in g_strdup ../glib/gstrfuncs.c:361
#4 0x7fa3b6e5e6b4 in g_variant_dup_string ../glib/gvariant.c:1543
#5 0x7fa3b70cd86d in g_settings_get_string ../gio/gsettings.c:1807
#6 0x404414 in settings_command_changed /home/robert/builddir.gcc/mate-applets/command/src/command.c:226
#7 0x7fa3b6f228ac in g_cclosure_marshal_VOID__STRINGv ../gobject/gmarshal.c:1462
#8 0x7fa3b6f1d2e1 in _g_closure_invoke_va ../gobject/gclosure.c:893
#9 0x7fa3b6f3e822 in g_signal_emit_valist ../gobject/gsignal.c:3407
#10 0x7fa3b6f3fd8e in g_signal_emit …
```
=> command: fix memory leak

battstat/battstat-upower.h, battstat/battstat.h, battstat/battstat_applet.c, battstat/power-management.c
```
CFLAGS="-g -O0 -Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-compile-warnings=maximum && make &> make.log
```
```
battstat_applet.c:729:36: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
battstat->last_charging = info.charging;
~ ~~~~~^~~~~~~~
--
battstat_applet.c:732:41: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
battstat->last_acline_status = info.on_ac_power;
~ ~~~~~^~~~~~~~~~~
```
=> battstat: implicit conversion changes signedness: 'gboolean' to 'guint'

command/src/command.c
```
command.c:472:45: warning: incompatible pointer types passing 'MatePanelApplet *' (aka 'struct _MatePanelApplet *') to parameter of type 'GtkWidget *' (aka 'struct _GtkWidget *') [-Wincompatible-pointer-types]
atk_widget = gtk_widget_get_accessible (command_applet->applet);
^~~~~~~~~~~~~~~~~~~~~~
/usr/include/gtk-3.0/gtk/gtkwidget.h:1067:79: note: passing argument to parameter 'widget' here
AtkObject*       gtk_widget_get_accessible               (GtkWidget          *widget);
^
```
=> command: fix -Wincompatible-pointer-types warning

.build.yml, configure.ac, stickynotes/sticky-notes-note.ui, stickynotes/stickynotes.c
GtkSourceBuffer provides the ability to undo or redo the change to the note text-body.  [pluma](https://github.com/mate-desktop/pluma/commit/69870af1aed34b32a48ff75554b4438e222cc526) uses gtksourceview 4, so we don't need to depend on two versions.
fix #634
=> stickynotes: bump gtksourceview 4

stickynotes/org.mate.stickynotes.gschema.xml.in, stickynotes/stickynotes_applet_callbacks.c
Add a new key value "click-hide",When this key is disabled, click the note icon on the panel, and the note will not be hidden
Fix #627 
1. make PR and install 
2. replace note from panel
3. run ```gsettings set org.mate.stickynotes click-hide false```
4. clicked note icon
=> Add click-hide key to the stickynotes GSettings

timerapplet/src/timerapplet.c
Ensure the timer applet can be clicked on with the left mouse button in wayland. Otherwise the timer cannot be started and stopped by clicking on the applet in wayland. Left-click goes through to the panel instead without this
=> Timer-catch the left click when under wayland

timerapplet/src/timerapplet.c
Fix `atk_object_set_description: assertion 'description != NULL' failed` warning when timer runs down. Looks like a race condition is present here. Ideally someone with a working orca install (errors out here) would test this, but the warning indicates that we would not be setting anything when` atk_object_set_description` gets called with an empty description anyway.
Alternately, we could set that description to "finished timer" but Orca should already speak the label text, which shows up in Accerciser
=> timer: fix in-process ATK warning

trashapplet/src/trashapplet.c
*the animation on this applet isn't visible anyway even out of process where it still runs
=> trash, in-process: fix segfault with glib 2.77.1

configure.ac, stickynotes/sticky-notes-note.ui, stickynotes/stickynotes.c, stickynotes/stickynotes.h, stickynotes/stickynotes_applet.c, stickynotes/stickynotes_applet_callbacks.c, stickynotes/util.c
Fix failure of stickynotes to show in both x11 and wayland, and wayland segfaults. Do not use GtkSourceView anymore since the current version is not working with stickynotes, use GtkTextView which works fine even if it has fewer features.
Also ensure that when in Wayland (or any future non-x11 windowing system) we don't call x11 specific functions
=> Fix stickynotes
