cpufreq/src/cpufreq-applet.c
In gtk3,  replacing "label" with "applet->label" makes the gtk_widget_get_preferred_width functions work for the frequency and unit labels without issue. Trim them a bit in gtk3.19 builds as they render 2px wider there for some reason. Two out of three options for text now work as they did in GTK2. 
The exception is the percentage label. That one apparently starts up with "0%" entered and does not seem to update its width when larger character strings come up.  This even though the label itself can be shown to be changing it's size with the length of the string by invoking the GTK 3.19 applet transparency issues with the label themed black. Thus, a fixed figure of 20px still has to be added to that one. On the other hand, that will ensure the applet never jumps from percentage changes. …
=> cpufreq  GTK3: hardcode fewer labels

cpufreq/src/cpufreq-monitor-libcpufreq.c
Should fix https://github.com/mate-desktop/mate-applets/issues/193
=> fix build with kernel-4.7

cpufreq/src/cpufreq-prefs.c
=> cpufreq-prefs: don't use deprecated gtk_show_uri

configure.ac, drivemount/Makefile.am, drivemount/drive-button.c, drivemount/drive-button.h, drivemount/drive-list.h, drivemount/drivemount.c, drivemount/org.mate.drivemount.gschema.xml.in
GSettings for checkmark color shown for mounted volumes.
=> GSettings for checkmark color shown for mounted volumes.

cpufreq/src/cpufreq-applet.c
Should work on horizontal panel with GTK+ 3.22.
Vertical panel has some issues, but it seems they were there already.
PangoLayout trick was stolen from GtkScale code:
https://git.gnome.org/browse/gtk+/tree/gtk/gtkscale.c?h=gtk-3-22#n1236
Need to test with GTK+ 3.18 as well...
=> cpufreq: fix calculating max width of frequency/unit/percent labels

multiload/properties.c
=> type mismatch in g_setting set value

charpick/charpick.c, cpufreq/src/cpufreq-applet.c, drivemount/drive-button.c, stickynotes/stickynotes_callbacks.c
=> replace deprecated gtk menu popup

mateweather/mateweather-applet.c, mateweather/mateweather-dialog.c, mateweather/mateweather-pref.c, stickynotes/util.c
=> replace deprecated gdk_error_trap_push/pop and  GtkAlignment

cpufreq/src/cpufreq-monitor-libcpufreq.c, trashapplet/src/trashapplet.c
Please test.
@flexiondotorg 
I guess you need to update your ubuntu patch for cpufreq.
=> Build warnings

timerapplet/timerapplet.c
=> timerapplet: Allow reseting timer when inactive

multiload/linux-proc.c
fixes https://github.com/mate-desktop/mate-applets/issues/230
origin commit:
https://gitlab.gnome.org/GNOME/gnome-applets/commit/daadbbc
Please test
=> multiload: ignore priviledged mount points

accessx-status/applet.c, battstat/battstat_applet.c, charpick/charpick.c, command/command.c, cpufreq/src/cpufreq-applet.c, drivemount/drivemount.c, geyes/geyes.c, mate-applets.pot, mateweather/mateweather-about.c, multiload/main.c, netspeed/src/netspeed.c, stickynotes/stickynotes_applet_callbacks.c, timerapplet/timerapplet.c, trashapplet/src/trashapplet.c
About dialog:
- Ensure proper translation of the title
- Make translatable copyright and update year
- Make translatable documenters
- Finaly, update pot file
=> i18n - about dialog

mateweather/mateweather-applet.c
fixes https://github.com/mate-desktop/mate-applets/issues/395
Please test.
=> weather: align Gtk_Box to center

cpufreq/src/cpufreq-monitor-libcpufreq.c, cpufreq/src/cpufreq-selector/cpufreq-selector-libcpufreq.c
fixes https://github.com/mate-desktop/mate-applets/issues/394
Please test.
=> cpufreq: support kernel 5.1.0

battstat/acpi-freebsd.c, battstat/acpi-freebsd.h, battstat/acpi-linux.c, battstat/acpi-linux.h, battstat/battstat-upower.c, battstat/battstat-upower.h, battstat/battstat.h, battstat/battstat_applet.c, battstat/power-management.c, battstat/properties.c
Update [FSF address](https://www.fsf.org/about/contact/)
=> Update FSF address

command/Makefile.am, command/command.c, command/ma-command.c, command/ma-command.h
Fixed #163 , please review, thank you.
=> Make command applet run commands asynchronously

configure.ac, drivemount/drive-button.c
=> I18n tooltip text: nothing to mount

accessx-status/Makefile.am, battstat/Makefile.am, charpick/Makefile.am, configure.ac, cpufreq/src/Makefile.am, drivemount/Makefile.am, geyes/Makefile.am, mateweather/Makefile.am, multiload/Makefile.am, netspeed/src/Makefile.am, stickynotes/Makefile.am, trashapplet/src/Makefile.am
Test:
```
$ ./autogen.sh --prefix=/usr --enable-compile-warnings=maximum && make V=1
```
=> build: Use WARN_CFLAGS variable

accessx-status/Makefile.am, battstat/Makefile.am, charpick/Makefile.am, command/Makefile.am, configure.ac, cpufreq/src/Makefile.am, cpufreq/src/cpufreq-selector.c, cpufreq/src/cpufreq-utils.c, drivemount/Makefile.am, geyes/Makefile.am, mateweather/Makefile.am, multiload/Makefile.am, netspeed/src/Makefile.am, stickynotes/Makefile.am, timerapplet/Makefile.am, trashapplet/src/Makefile.am
=> build: use dbus-glib only when required

man/mate-cpufreq-selector.1
=> mate-cpufreq-selector: Fix example in man page

mateweather/Makefile.am, mateweather/mateweather-applet.c, mateweather/mateweather-dialog.c, mateweather/mateweather-dialog.h, mateweather/mateweather-dialog.ui, mateweather/mateweather-resources.gresource.xml, mateweather/mateweather.h
Test: Open Weather Report Details dialog
=> mateweather: Add mateweather-dialog.ui

cpufreq/src/cpufreq-applet.c, cpufreq/src/cpufreq-applet.h
Only code-syle commit from https://github.com/mate-desktop/mate-applets/pull/517
=> Cpufreq deprecations

multiload/autoscaler.c, multiload/autoscaler.h, multiload/load-graph.c, multiload/load-graph.h, multiload/main.c, multiload/netspeed.c, multiload/properties.c
- tab to spaces
- fix some indents
=> multiload: improve code-style

accessx-status/src/applet.c, accessx-status/src/applet.h
- tab to spaces
- fix indents
- shorten lines
=> accessx-status: improve code-style

battstat/acpi-linux.c, battstat/acpi-linux.h, battstat/apmlib/apm.h, battstat/apmlib/apmlib.c, battstat/battstat-upower.c, battstat/battstat.h, battstat/battstat_applet.c, battstat/power-management.c
- tab to spaces
- fix indents
- add a space before brackets
=> battstat: improve code-style

charpick/charpick.c, charpick/charpick.h, charpick/properties.c
- tab to spaces
- fix indents
- shorten lines
=> charpick: improve code-style

drivemount/drive-button.c, drivemount/drive-button.h, drivemount/drive-list.c, drivemount/drive-list.h, drivemount/drivemount.c
- tabs to spaces
- 4 spaces at the beginning of a line
=> drivemount: improve code-style

Makefile.am
Test:
```
$ ./autogen.sh --prefix=/usr && make && make distcheck && make maintainer-clean
$ git status
```
=> build: make maintainer-clean

netspeed/src/netspeed.c
=> netspeed: show ipv6 address in tooltip if ipv4 address is not used

netspeed/src/backend.c, netspeed/src/backend.h, netspeed/src/ieee80211.h, netspeed/src/netspeed.c, netspeed/src/nl80211.h
- tabs to spaces
- start a new line with 4 spaces at the beginning
=> Netspeed code style

multiload/data/org.mate.panel.applet.multiload.gschema.xml.in, multiload/src/autoscaler.c, multiload/src/autoscaler.h, multiload/src/global.h, multiload/src/linux-proc.c, multiload/src/linux-proc.h, multiload/src/load-graph.c, multiload/src/load-graph.h, multiload/src/main.c, multiload/src/netspeed.c, multiload/src/properties.c
=> multiload: increase refresh rate range setting

netspeed/data/netspeed-details.ui, netspeed/src/backend.c, netspeed/src/backend.h, netspeed/src/netspeed.c
=> netspeed: show all ipv6 addrs in device details dialog

stickynotes/stickynotes.c, stickynotes/stickynotes.h, stickynotes/stickynotes_applet.c, stickynotes/stickynotes_applet.h, stickynotes/stickynotes_applet_callbacks.c, stickynotes/stickynotes_applet_callbacks.h, stickynotes/stickynotes_callbacks.c, stickynotes/stickynotes_callbacks.h, stickynotes/util.c, stickynotes/util.h
- tabs to spaces
- shortened lines
- etc.
=> Stickynotes codestyle

accessx-status/src/applet.c, battstat/battstat_applet.c, cpufreq/src/cpufreq-applet.c, cpufreq/src/cpufreq-monitor-libcpufreq.c, cpufreq/src/cpufreq-monitor-sysfs.c, mateweather/src/mateweather-applet.c, stickynotes/stickynotes.c
test:
```
grep -n -R '($' --include=*.c
```
=> Don't leave any round bracket at line end

netspeed/src/backend.c, netspeed/src/backend.h, netspeed/src/netspeed.c
=> netspeed: Show all IPv4 and IPv6 addresses in tooltip

accessx-status/src/applet.c, battstat/battstat-upower.c, battstat/battstat_applet.c, battstat/power-management.c, charpick/charpick.c, charpick/properties.c, command/src/command.c, cpufreq/src/cpufreq-applet.c, cpufreq/src/cpufreq-popup.c, cpufreq/src/cpufreq-prefs.c, cpufreq/src/cpufreq-utils.c, drivemount/src/drive-button.c, geyes/src/geyes.c, geyes/src/themes.c, mateweather/src/mateweather-applet.c, mateweather/src/mateweather-pref.c, multiload/src/load-graph.c, multiload/src/main.c, stickynotes/stickynotes.c, stickynotes/stickynotes_applet_callbacks.c, timerapplet/src/timerapplet.c, trashapplet/src/trashapplet.c
- instance and detailed-signal on the same line
=> Remove unnecessary casts on g_signal_connect calls

netspeed/src/backend.c, netspeed/src/backend.h, netspeed/src/netspeed-preferences.c, netspeed/src/netspeed.c
=> netspeed: listing available devices

configure.ac, netspeed/src/netspeed.c
Test:
```
$ grep PACKAGE_URL config.h
#define PACKAGE_URL "https://mate-desktop.org"
```
=> build: Use PACKAGE_URL variable

trashapplet/src/trash-empty.c
Use ```g_task``` replaces the deprecated ```g_io_scheduler```, removing compilation warnings
```
trash-empty.c: In function 'trash_empty_job':
trash-empty.c:217:3: warning: 'g_io_scheduler_job_send_to_mainloop_async' is deprecated: Use 'g_main_context_invoke' instead [-Wdeprecated-declarations]
g_io_scheduler_job_send_to_mainloop_async (job,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gio/gio.h:89,
from trash-empty.c:22:
/usr/include/glib-2.0/gio/gioscheduler.h:47:10: note: declared here
void     g_io_scheduler_job_send_to_mainloop_async (GIOSchedulerJob     *job,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
trash-empty.c: In function 'trash_empty_start':
trash-empty.c:267:3: warning: 'g_io_scheduler_push_job' is deprecated: Use '"GThreadPool or …
```
=> trashapplet: Replace the deprecated function

battstat/Makefile.am, battstat/apmlib/Makefile.am, configure.ac
See https://github.com/mate-desktop/mate-applets/pull/651#issuecomment-1599632724
=> battstat: Use libtool to build libapm

invest-applet/invest/Makefile.am, invest-applet/invest/invest-applet-chart.c, invest-applet/invest/invest-applet-chart.h, invest-applet/invest/invest-applet.c, invest-applet/invest/invest-applet.h
Adds a chart window that shows stock price history over a configurable time scale.
=> invest: Add chart with stock price history
